services:
  ubuntu_service:
    build: .
    container_name: ubu
    image: ubui:latest
    ports:
      - 8080-8089:8080-8089
    volumes:
      - ../.:/app
    working_dir: /app
    stdin_open: true  # Keeps STDIN open for interactive shell
    tty: true         # Allocates a pseudo-TTY